Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/purpose': '@stable'
    'frameworks/sonnet': '@stable'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
