/***************************************************************************
                          icons.h  -  description                              
                             -------------------                                         
    begin                : Sat Jan 1 2000                                           
    copyright            : (C) 2000 by Klaas Freitag                         
    email                :                                      
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   * 
 *                                                                         *
 ***************************************************************************/

#ifndef _ICONS_H
#define _ICONS_H

/* XPM */
static const char*mini_color[]={
"16 16 19 1",
"m c #008000",
"e c #ffa858",
"q c #000080",
"g c #c0c000",
"l c #00ff00",
"i c #808000",
"a c #ffc0c0",
"n c #c0c0ff",
"# c #000000",
"d c #ff8000",
"o c #0000c0",
"j c #c0ffc0",
"h c #ffff00",
"c c #ffdca8",
"f c #ffffc0",
"p c #0000ff",
". c None",
"k c #00c000",
"b c #ff0000",
"................",
"................",
"................",
"................",
"######..........",
"#aabb#..........",
"#aabb##.........",
"#ccdedd#........",
"#dddedd###......",
"#ffghggii#......",
"#ggghggii###....",
"#jjklkkmmmm#....",
"#kkklkkmmmm#....",
"#nnopooqoqq#....",
"#nnopooqoqq#....",
"############...."};

/* XPM */
static const char*mini_gray[]={
"16 16 8 1",
"e c #808080",
"d c #a0a0a0",
"c c #c3c3c3",
"# c #000000",
". c None",
"f c #585858",
"b c #dcdcdc",
"a c #ffffff",
"................",
"................",
"................",
"................",
"######..........",
"#aabb#..........",
"#aabb##.........",
"#bbcbcc#........",
"#cccbcc###......",
"#dddddddd#......",
"#dddddddd###....",
"#eeeeeeeeee#....",
"#eeeeeeeee##....",
"#ffffffff###....",
"#fffffff####....",
"############...."};

/* XPM */
static const char*mini_lineart[]={
"16 16 3 1",
"# c #000000",
". c None",
"a c #ffffff",
"................",
"................",
"................",
"................",
"######..........",
"#aaaa#..........",
"#aaaa##.........",
"#aaaaaa#........",
"#aaaaaa###......",
"#aaaaaaaa#......",
"#aaaaaaaa###....",
"############....",
"############....",
"############....",
"############....",
"############...."};

/* XPM */
static const char*mini_folder[]={
"16 16 9 1",
"g c #808080",
"b c #ffa858",
"e c #c0c0c0",
"# c #000000",
"c c #ffdca8",
". c None",
"a c #585858",
"f c #a0a0a4",
"d c #ffffff",
"..#a#...........",
".#abc##.........",
".#daabc#####....",
".#ddeaabcccb#...",
".#dedeeabccca...",
".#edeeeeaaaab#..",
".#deeeeeeefe#ba.",
".#eeeeeeefef#ba.",
".#eeeeeefeff#ba.",
".#eeeeefefff#ba.",
".##geefeffff#ba.",
"...##gefffff#ba.",
".....##fffff#ba.",
".......##fff#b##",
".........##f#b##",
"...........####."};

/* XPM */
static const char*mini_floppy[]={
"16 16 11 1",
"g c #808080",
"h c #a0a0a4",
"f c #c0c0c0",
"e c #000080",
"# c #000000",
"c c #0000c0",
"b c #303030",
"a c #0000ff",
". c None",
"i c #dcdcdc",
"d c #ffffff",
".......#........",
"......#ab#......",
".....#acdd##....",
"....#acddddd##..",
"...#acdddddddc##",
"..#aeaacddddcae#",
".#aefeeaacdcae#.",
"#aefaffeeacae#..",
"#egfffhaaeae#...",
".##gihaaeae#....",
"...##gaeae#.....",
".....##ee#......",
".......##.......",
"................",
"................",
"................"};

/* XPM */
static const char * mini_ray[] = {
"16 14 4 1",
" 	c None",
".	c black",
"X	c yellow",
"o	c gray50",
"     .........  ",
"     .XXXXXX.o  ",
"    .XXXXXX.o   ",
"    .XXXXX.o    ",
"   .XXXXX.o     ",
"   .XXXX.....   ",
"  .XXXXXXXX.o   ",
"  .....XXX.o    ",
"   oo.XXX.o     ",
"     .XX.o      ",
"    .XX.o       ",
"    .X.o        ",
"   .X.o         ",
"   ..o          "};

/* XPM */
static const char*mini_folder_new[]={
"16 16 14 1",
"k c #808080",
"d c #ffa858",
"i c #c0c000",
"c c #000080",
"j c #c0c0c0",
"# c #000000",
"h c #0000c0",
"b c #ffff00",
"e c #ffdca8",
". c None",
"a c #585858",
"l c #a0a0a4",
"g c #ffffff",
"f c #ff0000",
"..#a#.....bcbcb.",
".#ade##..bcfbfcb",
".#gaade#bhbbibbc",
".#ggjaadebcfbfcb",
".#gjgjjadebcbcb.",
".#jgjjjjaaabcbk.",
".#gjjjjjjjljbda.",
".#jjjjjjjljl#da.",
".#jjjjjjljll#da.",
".#jjjjjljlll#da.",
".##kjjljllll#da.",
"...##kjlllll#da.",
".....##lllll#da.",
".......##lll#d##",
".........##l#d##",
"...........####."};

/* XPM */
/* Drawn for the K Desktop Environment */
/* See http://www.kde.org */
static const char*mini_trash[]={
"16 16 11 1",
"h c #000000",
". c None",
"d c #004040",
"f c #c0c0c0",
"i c #585858",
"b c #a0a0a4",
"a c #dcdcdc",
"# c #000000",
"g c #808080",
"c c #404000",
"e c #ffffff",
".....##a#.......",
"..###abcd####...",
".#eeefffghffb#..",
".#abfeeeffiii#..",
"..dgaabbbbgg#...",
"..#bbbggiigi#...",
"..#bebagggii#...",
"..#bebagggii#...",
"..#bebagggii#...",
"..#bebagggii#...",
"..#bebagggii#...",
"..#bebagggii#...",
"..#bebagggii#...",
"..#aebagggii#...",
"...##aabbg##....",
".....#####......"};

/* XPM */
static const char*mini_scan[]={
"16 16 11 1",
"g c #808080",
"d c #008000",
"a c #ffa858",
"e c #00ff00",
"b c #c05800",
"# c #000000",
"i c #303030",
"c c #ffdca8",
". c None",
"f c #00c000",
"h c #dcdcdc",
"................",
"#########.......",
"#aaaaaaaab......",
".#accccccab.....",
"..#accccccab....",
"...#accccccab...",
"...##accccccab..",
"..#bd#aaaaaaaab.",
".#befd#########.",
"#bghefdhhhgbbi..",
"#bbghefdhgbbi...",
".ibbghefgbbi....",
"..ibbghgbbi.....",
"...ibbgbbi......",
"....ibbbi.......",
".....ibi........"};


/* XPM */
static const char*mini_ocr[]={
"16 16 3 1",
"a c #c0c0ff",
"# c #0000c0",
". c None",
"................",
"...###..........",
"..#aaa#.........",
".#a....#a.......",
".#a....#a.......",
".#a....###......",
"..#aaa#aa##.....",
"...###a.........",
".....#a...###aa.",
".....#a...#a.#a.",
"......#aaa#a.#a.",
".......#######a.",
"..........##a...",
"..........#a#a..",
"..........#a.#..",
"................"};

/* XPM */
static const char*mini_preview[]={
"16 16 22 1",
"a c #808080",
"s c #008000",
"k c #ffa858",
"m c #c0c000",
"b c #000080",
"r c #00ff00",
"o c #808000",
"h c #ffc0c0",
"t c #c0c0ff",
"f c #000000",
"j c #ff8000",
"e c #0000c0",
"p c #c0ffc0",
"n c #ffff00",
"# c #303030",
"i c #ffdca8",
"l c #ffffc0",
"d c #0000ff",
". c None",
"g c #585858",
"q c #00c000",
"c c #ffffff",
".......######...",
".....##aabbba#..",
"...##aacbdddbc#.",
"..#aaccbdeeedbc#",
"f#accccbdegedbc#",
"fh#acccbdeeedbc#",
"fhh#aaccbdddbc#.",
"fiij##aaabbba#..",
"fjjjkjj##a###...",
"fllmnmmoof......",
"fmmmnmmoofff....",
"fppqrqqssssf....",
"fqqqrqqssssf....",
"fttedeebebbf....",
"fttedeebebbf....",
"ffffffffffff...."};

/* XPM */
static const char*mini_colorlock[]={
"16 16 20 1",
"# c #808080",
"i c #ffa858",
"f c #c0c000",
"b c #000080",
"o c #00ff00",
"j c #808000",
"d c #ffc0c0",
"p c #c0c0ff",
"c c #000000",
"h c #ff8000",
"q c #0000c0",
"m c #c0ffc0",
"l c #ffff00",
"a c #303030",
"g c #ffdca8",
"k c #ffffc0",
"r c #0000ff",
". c None",
"n c #00c000",
"e c #ff0000",
".........#####..",
"........##aaa##.",
"........#b...a#.",
"........#a...a#.",
"cccccc..#a...a#.",
"cddeeeaaaaaaaa#a",
"cddeeeaffffffa#a",
"cgghihafjjjjjjfa",
"chhhihafjjjjjjfa",
"ckkflfafjjjjjjfa",
"cffflfafjjjjjjfa",
"cmmnonafjjjjjjfa",
"cnnnonaffffffffa",
"cppqrqaaaaaaaaaa",
"cppqrqqbqbbb....",
"cccccccccccc...."};

/* XPM */
static const char*mini_fitwidth[]={
"10 14 7 1",
"d c #000080",
". c #000000",
"c c #0000ff",
"e c #008080",
"# c None",
"b c #dcdcdc",
"a c #ffffff",
".......###",
".aaaabb.##",
".aaaa#ab.#",
".aaaa#aab.",
".aaaa#....",
".acaaa#c#.",
".cdeeeedc.",
"cccccccccc",
".cdeeeedc.",
".acaaaaca.",
".aaaaaaaa.",
".aaaaaaaa.",
".aaaaaaaa.",
".........."};

/* XPM */
static const char*mini_fitheight[]={
"10 14 7 1",
". c #000000",
"d c #0000c0",
"# c #0000ff",
"e c #008080",
"a c None",
"c c #dcdcdc",
"b c #ffffff",
"....#..aaa",
".bb###c.aa",
".b#d#d#c.a",
".bbe#ebbc.",
".bbe#e....",
".bbe#eaaa.",
".bbe#ebbb.",
".bbe#ebbb.",
".bbe#ebbb.",
".bbe#ebbb.",
".bbe#ebbb.",
".b#d#d#bb.",
".bb###bbb.",
"....#....."};

#endif
